#!/bin/sh
set -e

# Configurable.
sed -i 's@%PHPFPM_LISTEN%@'"${PHPFPM_LISTEN}"'@' /usr/local/etc/php-fpm.d/www.conf
sed -i 's@%PHPFPM_PM_MAX_CHILDREN%@'"${PHPFPM_PM_MAX_CHILDREN}"'@' /usr/local/etc/php-fpm.d/www.conf
sed -i 's@%PHPFPM_PM_START_SERVERS%@'"${PHPFPM_PM_START_SERVERS}"'@' /usr/local/etc/php-fpm.d/www.conf
sed -i 's@%PHPFPM_PM_MIN_SPARE_SERVERS%@'"${PHPFPM_PM_MIN_SPARE_SERVERS}"'@' /usr/local/etc/php-fpm.d/www.conf
sed -i 's@%PHPFPM_PM_MAX_SPARE_SERVERS%@'"${PHPFPM_PM_MAX_SPARE_SERVERS}"'@' /usr/local/etc/php-fpm.d/www.conf
sed -i 's@%PHP_MAX_EXECUTION_TIME%@'"${PHP_MAX_EXECUTION_TIME}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_MEMORY_LIMIT%@'"${PHP_MEMORY_LIMIT}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_REALPATH_CACHE_SIZE%@'"${PHP_REALPATH_CACHE_SIZE}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_REALPATH_CACHE_TTL%@'"${PHP_REALPATH_CACHE_TTL}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_MAX_INPUT_VARS%@'"${PHP_MAX_INPUT_VARS}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_POST_MAX_SIZE%@'"${PHP_POST_MAX_SIZE}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_UPLOAD_MAX_FILESIZE%@'"${PHP_UPLOAD_MAX_FILESIZE}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_SENDMAIL_PATH%@'"${PHP_SENDMAIL_PATH}"'@' /usr/local/etc/php/php.ini
sed -i 's@%PHP_CLI_MAX_EXECUTION_TIME%@'"${PHP_CLI_MAX_EXECUTION_TIME}"'@' /usr/local/etc/php/php-cli.ini
sed -i 's@%PHP_CLI_MEMORY_LIMIT%@'"${PHP_CLI_MEMORY_LIMIT}"'@' /usr/local/etc/php/php-cli.ini
sed -i 's@%PHP_CLI_REALPATH_CACHE_SIZE%@'"${PHP_CLI_REALPATH_CACHE_SIZE}"'@' /usr/local/etc/php/php-cli.ini
sed -i 's@%PHP_CLI_REALPATH_CACHE_TTL%@'"${PHP_CLI_REALPATH_CACHE_TTL}"'@' /usr/local/etc/php/php-cli.ini
sed -i 's@%PHP_CLI_SENDMAIL_PATH%@'"${PHP_CLI_SENDMAIL_PATH}"'@' /usr/local/etc/php/php-cli.ini
sed -i 's/^mailhub=.*/mailhub='"${SSMTP_MAILHUB}"'/' /etc/ssmtp/ssmtp.conf

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
